part of '../main.dart';

class BriefPage extends StatefulWidget { const BriefPage({super.key, required this.api, required this.user, this.language = 'en', this.onSaved, this.initial, this.projectId, this.simulation = false}); final ApiClient api; final Map<String, dynamic> user; final String language; final VoidCallback? onSaved; final Map<String, dynamic>? initial; final String? projectId; final bool simulation; @override State<BriefPage> createState() => _BriefPageState(); }
class _BriefPageState extends State<BriefPage> {
  final form = GlobalKey<FormState>();
  final controls = <String, TextEditingController>{};
  late Future<dynamic> catalog = Future.wait([widget.api.get('/api/catalog/foods'), widget.api.get('/api/catalog/materials')]);
  String foodId = 'khakhra', storage = 'ambient', equipment = 'hand_sealer', priority = 'balanced', current = '';
  bool expert = false, saving = false, listening = false; String? error;
  List<Map<String, dynamic>> stages = [];
  final speech = SpeechToText();
  final defaults = <String, dynamic>{'name': '', 'weight_g': 250, 'area_m2': .06, 'headspace_ml': 250, 'target_days': 14, 'temperature_c': 25, 'relative_humidity': 65, 'budget_inr': 10, 'food_value_inr': 50, 'loss_percent': 5, 'packing_inr': .5, 'logistics_inr': 1, 'problem': '', 'moisture_pct': '', 'water_activity': '', 'fat_pct': '', 'ph': '', 'respiration_ml_kg_h': ''};
  @override void initState() { super.initState(); final initial = widget.initial; for (final e in defaults.entries) { controls[e.key] = TextEditingController(text: '${initial?[e.key] ?? e.value}'); } if (initial != null) { foodId = initial['food_id'] as String; storage = initial['storage_type'] as String; equipment = initial['equipment'] as String; priority = initial['priority'] as String; current = initial['current_material_id'] as String? ?? ''; stages = asRows(initial['stages'] ?? []); expert = initial['mode'] == 'expert'; } else { expert = widget.user['role'] != 'farmer'; } }
  @override void dispose() { for (final c in controls.values) { c.dispose(); } speech.stop(); super.dispose(); }
  String label(String key, String english) { const labels = {'hi': {'food': 'खाद्य वस्तु', 'name': 'परियोजना का नाम', 'weight_g': 'प्रति पैक वजन (ग्राम)', 'target_days': 'लक्षित अवधि (दिन)', 'temperature_c': 'तापमान (°C)', 'relative_humidity': 'सापेक्ष आर्द्रता (%)', 'budget_inr': 'पैक बजट (₹)'}, 'gu': {'food': 'ખાદ્ય વસ્તુ', 'name': 'પ્રોજેક્ટનું નામ', 'weight_g': 'પેકનું વજન (ગ્રામ)', 'target_days': 'લક્ષિત દિવસો', 'temperature_c': 'તાપમાન (°C)', 'relative_humidity': 'ભેજ (%)', 'budget_inr': 'પેક બજેટ (₹)'}, 'mr': {'food': 'अन्नपदार्थ', 'name': 'प्रकल्पाचे नाव', 'weight_g': 'पॅकचे वजन (ग्रॅम)', 'target_days': 'लक्षित दिवस', 'temperature_c': 'तापमान (°C)', 'relative_humidity': 'सापेक्ष आर्द्रता (%)', 'budget_inr': 'पॅक बजेट (₹)'}}; return labels[widget.language]?[key] ?? english; }
  Widget field(String key, String title, {bool optional = false, bool text = false}) => SizedBox(width: 275, child: TextFormField(controller: controls[key], decoration: InputDecoration(labelText: label(key, title), helperText: optional ? 'Optional · profile default if blank' : null), maxLines: key == 'problem' ? 2 : 1, keyboardType: text ? TextInputType.text : const TextInputType.numberWithOptions(decimal: true, signed: true), validator: (v) { if ((v == null || v.trim().isEmpty)) return optional ? null : 'Required'; if (text) return key == 'name' && v.trim().length < 2 ? 'Enter at least two characters' : null; final n = double.tryParse(v); return n == null || !n.isFinite ? 'Enter a valid number' : null; }));
  Widget select(String title, String value, Map<String, String> items, void Function(String) change) => SizedBox(width: 275, child: DropdownButtonFormField<String>(value: value, isExpanded: true, decoration: InputDecoration(labelText: title), items: items.entries.map((e) => DropdownMenuItem(value: e.key, child: Text(e.value, overflow: TextOverflow.ellipsis))).toList(), onChanged: (v) => setState(() => change(v!))));
  Map<String, dynamic> payload() => {'name': controls['name']!.text.trim(), 'food_id': foodId, 'mode': expert ? 'expert' : 'simple', 'storage_type': storage, 'equipment': equipment, 'priority': priority, 'current_material_id': current.isEmpty ? null : current, 'stages': stages, 'problem': controls['problem']!.text.trim(), for (final key in controls.keys.where((k) => k != 'name' && k != 'problem')) key: controls[key]!.text.trim().isEmpty ? null : double.parse(controls[key]!.text.trim())};
  Future<void> save({bool preview = false}) async {
    if (!form.currentState!.validate()) return;
    setState(() { saving = true; error = null; });
    try {
      final body = payload();
      final path = preview ? '/api/recommendations/preview' : widget.projectId == null ? '/api/projects' : '/api/projects/${widget.projectId}/${widget.simulation ? 'simulate' : 'revise'}';
      final result = asMap(await widget.api.post(path, body));
      if (!mounted) return;
      if (preview || widget.simulation) { await Navigator.push(context, MaterialPageRoute<void>(builder: (_) => Scaffold(appBar: AppBar(title: Text(preview ? 'Preview • not saved' : 'What-if comparison • not saved')), body: PageBody(children: [if (widget.simulation) ...[Panel(child: Text('Baseline: ${(result['baseline']['candidates'] as List).length} candidates → Scenario: ${(result['scenario']['candidates'] as List).length} candidates')), const SizedBox(height: 16)], ResultView(result: preview ? result : asMap(result['scenario']))])))); }
      else if (widget.projectId != null) { Navigator.pop(context, true); toast(context, 'A new revision has been saved.'); }
      else { await openProject(context, widget.api, widget.user, result['id'] as String); widget.onSaved?.call(); }
    } catch (e) { if (mounted) setState(() => error = e.toString()); }
    finally { if (mounted) setState(() => saving = false); }
  }
  Future<void> addStage() async {
    await editDialog(context, 'Add journey stage', const [FormItem('name', 'Stage name', value: 'Transport'), FormItem('days', 'Duration (days)', numeric: true), FormItem('temperature_c', 'Temperature (°C)', numeric: true, value: '25'), FormItem('relative_humidity', 'Humidity (%)', numeric: true, value: '65')], (v) async { final days = double.parse(v['days']!); if (days <= 0 || stages.length >= 10) throw const ApiException(422, 'Use positive durations and at most 10 stages'); setState(() => stages.add({'name': v['name'], 'days': days, 'temperature_c': double.parse(v['temperature_c']!), 'relative_humidity': double.parse(v['relative_humidity']!)})); });
  }
  Future<void> voice() async {
    if (listening) { await speech.stop(); if (mounted) setState(() => listening = false); return; }
    final available = await speech.initialize(onStatus: (status) { if (mounted && status != 'listening') setState(() => listening = false); }, onError: (e) { if (mounted) { setState(() => listening = false); toast(context, e.errorMsg); } });
    if (!available) { if (mounted) toast(context, 'Speech recognition is unavailable or microphone permission was denied. You can type your input.'); return; }
    final prefix = widget.language;
    final locales = await speech.locales();
    final supported = locales.where((l) => l.localeId.toLowerCase().startsWith(prefix)).toList();
    if (supported.isEmpty) { if (mounted) toast(context, 'This language is not installed for speech on this device.'); return; }
    if (mounted) setState(() => listening = true);
    await speech.listen(localeId: supported.first.localeId, onResult: (result) { controls['problem']!.text = result.recognizedWords; }, listenFor: const Duration(seconds: 30));
  }
  @override Widget build(BuildContext context) => PageBody(children: [Heading(widget.simulation ? 'Explore a what-if scenario' : widget.projectId != null ? 'Create a project revision' : 'Find the right packaging', subtitle: 'Start with your product. We will make the assumptions visible.'), LoadView(future: catalog, retry: () => setState(() => catalog = Future.wait([widget.api.get('/api/catalog/foods'), widget.api.get('/api/catalog/materials')])), builder: (raw) { final foods = asRows(raw[0]), materials = asRows(raw[1]); final food = foods.firstWhere((f) => f['id'] == foodId); return Form(key: form, child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
    Panel(child: Row(children: [const Icon(Icons.tune_rounded, color: green), const SizedBox(width: 12), const Expanded(child: Text('Expert inputs', style: TextStyle(fontWeight: FontWeight.w700))), Switch(value: expert, onChanged: (v) => setState(() => expert = v))])), const SizedBox(height: 20),
    Panel(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const SectionTitle('01', 'Tell us about your product'), const SizedBox(height: 22), Wrap(spacing: 18, runSpacing: 20, children: [field('name', 'Project name', text: true), select(label('food', 'Commodity / food'), foodId, {for (final f in foods) f['id'] as String: '${f['name']} · ${f['aliases']}'}, (v) { foodId = v; final f = foods.firstWhere((f) => f['id'] == v); storage = f['suggested_storage'] as String; controls['temperature_c']!.text = f['category'] == 'fresh' ? '12' : f['category'] == 'frozen' ? '-18' : '25'; controls['target_days']!.text = f['category'] == 'fresh' ? '5' : '14'; }), field('weight_g', 'Weight per pack (g)'), field('target_days', 'Target shelf life (days)'), field('budget_inr', 'Packaging budget (₹ / pack)'), field('problem', 'What problem are you seeing?', text: true, optional: true)]), const SizedBox(height: 14), TextButton.icon(onPressed: () => action(context, voice), icon: Icon(listening ? Icons.stop_circle_outlined : Icons.mic_none_rounded), label: Text(listening ? 'Stop listening' : 'Describe the problem by voice')), const Text('Review the recognised text before submitting. No numbers are applied automatically.', style: TextStyle(color: muted, fontSize: 12)), const SizedBox(height: 12), ExpansionTile(tilePadding: EdgeInsets.zero, title: const Text('Food profile assumptions', style: TextStyle(fontSize: 14, fontWeight: FontWeight.w700)), children: [DataView(data: {'State': food['state'], 'Moisture %': food['moisture_pct'], 'Water activity': food['water_activity'], 'Fat %': food['fat_pct'], 'pH': food['ph'], 'Source': food['source'], 'Limitations': food['limitations']})])])),
    const SizedBox(height: 20), Panel(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const SectionTitle('02', 'Storage, handling & priorities'), const SizedBox(height: 22), Wrap(spacing: 18, runSpacing: 20, children: [select('Storage type', storage, const {'ambient': 'Ambient', 'chilled': 'Chilled', 'frozen': 'Frozen'}, (v) => storage = v), field('temperature_c', 'Storage temperature (°C)'), field('relative_humidity', 'Relative humidity (%)'), select('Sealing equipment', equipment, const {'hand_sealer': 'Hand sealer', 'band_sealer': 'Band sealer', 'ffs': 'Form-fill-seal', 'tray_sealer': 'Tray sealer', 'unsealed': 'Unsealed'}, (v) => equipment = v), select('Optimise for', priority, const {'balanced': 'Balanced performance', 'cost': 'Lowest packaging cost', 'sustainability': 'Material & recovery'}, (v) => priority = v), select('Current packaging (for audit)', current, {'': 'Not currently selected', for (final m in materials) m['id'] as String: m['name'] as String}, (v) => current = v)]), const SizedBox(height: 20), const Text('Transport & storage journey', style: TextStyle(fontWeight: FontWeight.w700)), const SizedBox(height: 6), const Text('Optional. Stage durations must add up to your target days.', style: TextStyle(color: muted, fontSize: 12)), ...stages.asMap().entries.map((e) => ListTile(contentPadding: EdgeInsets.zero, title: Text('${e.value['name']} · ${e.value['days']} days'), subtitle: Text('${e.value['temperature_c']} °C · ${e.value['relative_humidity']}% RH'), trailing: IconButton(tooltip: 'Remove stage', onPressed: () => setState(() => stages.removeAt(e.key)), icon: const Icon(Icons.close)))), TextButton.icon(onPressed: stages.length >= 10 ? null : addStage, icon: const Icon(Icons.add), label: const Text('Add journey stage'))])),
    const SizedBox(height: 20), Panel(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const SectionTitle('03', 'Pack geometry & cost assumptions'), const SizedBox(height: 22), Wrap(spacing: 18, runSpacing: 20, children: [field('area_m2', 'Exposed film area (m²)'), field('headspace_ml', 'Headspace volume (mL)'), field('food_value_inr', 'Food value per pack (₹)'), field('loss_percent', 'Assumed product loss (%)'), field('packing_inr', 'Packing operations (₹ / pack)'), field('logistics_inr', 'Logistics (₹ / pack)')])])),
    if (expert) ...[const SizedBox(height: 20), Panel(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const SectionTitle('04', 'Measured food properties'), const SizedBox(height: 22), Wrap(spacing: 18, runSpacing: 20, children: [field('moisture_pct', 'Moisture content (%)', optional: true), field('water_activity', 'Water activity (0–1)', optional: true), field('fat_pct', 'Oil / fat content (%)', optional: true), field('ph', 'pH (0–14)', optional: true), field('respiration_ml_kg_h', 'Respiration (mL/kg/hour)', optional: true)])]))],
    const SizedBox(height: 20), if (error != null) ...[Panel(color: const Color(0xFFFFEDE6), child: Text(error!)), const SizedBox(height: 20)], Wrap(spacing: 14, runSpacing: 12, children: [FilledButton.icon(onPressed: saving ? null : () => save(), icon: const Icon(Icons.auto_awesome_outlined), label: Text(saving ? 'Analysing…' : widget.simulation ? 'Compare scenario' : widget.projectId != null ? 'Save new revision' : 'Generate recommendation')), OutlinedButton(onPressed: saving ? null : () => save(preview: true), child: const Text('Preview without saving'))]), const SizedBox(height: 24),
  ])); })]);
}
class SectionTitle extends StatelessWidget { const SectionTitle(this.number, this.title, {super.key}); final String number, title; @override Widget build(BuildContext context) => Row(children: [Container(padding: const EdgeInsets.all(9), decoration: BoxDecoration(color: paper, borderRadius: BorderRadius.circular(9)), child: Text(number, style: const TextStyle(color: green, fontWeight: FontWeight.w800, fontSize: 12))), const SizedBox(width: 12), Expanded(child: Text(title, style: Theme.of(context).textTheme.titleLarge))]); }
