part of '../main.dart';

class ProjectPage extends StatefulWidget { const ProjectPage({super.key, required this.api, required this.user, required this.id}); final ApiClient api; final Map<String, dynamic> user; final String id; @override State<ProjectPage> createState() => _ProjectPageState(); }
class _ProjectPageState extends State<ProjectPage> {
  late Future<dynamic> data = widget.api.get('/api/projects/${widget.id}'); bool busy = false; int section = 0;
  void reload() { if (mounted) setState(() => data = widget.api.get('/api/projects/${widget.id}')); }
  Future<void> work(Future<void> Function() task) async { setState(() => busy = true); await action(context, task); if (mounted) setState(() => busy = false); }
  Future<void> edit(Map<String, dynamic> p, {bool simulate = false}) async { await Navigator.push(context, MaterialPageRoute<void>(builder: (_) => Scaffold(appBar: AppBar(title: Text(simulate ? 'What-if simulator' : 'New revision')), body: BriefPage(api: widget.api, user: widget.user, initial: asMap(p['inputs']), projectId: widget.id, simulation: simulate)))); reload(); }
  Future<void> cache(Map<String, dynamic> p) async { final report = await widget.api.bytes('/api/projects/${widget.id}/report'); final key = 'offline_${widget.user['id']}_${widget.id}'; await widget.api.prefs?.setString(key, jsonEncode({'project': p, 'report': base64Encode(report), 'saved_at': DateTime.now().toIso8601String()})); if (mounted) toast(context, 'Project and PDF saved for offline access.'); }
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Packaging project'), actions: [IconButton(tooltip: 'Refresh', onPressed: reload, icon: const Icon(Icons.refresh)), const SizedBox(width: 16)]), body: LoadView(future: data, retry: reload, builder: (raw) { final p = asMap(raw), canEdit = p['can_edit'] == true, result = asMap(p['result']); return PageBody(children: [
    Heading(p['name'] as String, subtitle: '${p['food_name']} · Revision ${p['revision']} · ${p['target_days']} days', action: Pill(human(p['status']))),
    Wrap(spacing: 10, runSpacing: 10, children: [FilledButton.icon(onPressed: busy ? null : () => work(() async { await widget.api.download('/api/projects/${widget.id}/report', 'PackWise-${widget.id.substring(0, 8)}', 'pdf'); if (mounted) toast(context, 'PDF saved.'); }), icon: const Icon(Icons.download_outlined), label: const Text('Download specification')), if (canEdit) ...[OutlinedButton.icon(onPressed: busy ? null : () => edit(p, simulate: true), icon: const Icon(Icons.tune), label: const Text('What if?')), OutlinedButton.icon(onPressed: busy ? null : () => edit(p), icon: const Icon(Icons.edit_outlined), label: const Text('New revision')), OutlinedButton.icon(onPressed: busy ? null : () => work(() => cache(p)), icon: const Icon(Icons.offline_pin_outlined), label: const Text('Save offline')), OutlinedButton.icon(onPressed: busy ? null : () => work(() async { await widget.api.post('/api/projects/${widget.id}/share-review', {'enabled': p['shared_for_review'] != true}); reload(); }), icon: const Icon(Icons.fact_check_outlined), label: Text(p['shared_for_review'] == true ? 'Revoke review sharing' : 'Share for expert review'))]]),
    const SizedBox(height: 22), Wrap(spacing: 8, runSpacing: 8, children: ['Recommendations', 'Journey & sensors', 'Evidence & history', 'Advisor & sourcing'].asMap().entries.map((e) => ChoiceChip(label: Text(e.value), selected: section == e.key, onSelected: (_) => setState(() => section = e.key))).toList()), const SizedBox(height: 22),
    if (section == 0) ResultView(result: result, selectedId: p['selected_material_id'] as String?, onSelect: canEdit ? (id) => work(() async { await widget.api.post('/api/projects/${widget.id}/select', {'material_id': id}); reload(); }) : null, onTrial: canEdit ? (id) => recordTrial(context, widget.api, widget.id, id) : null),
    if (section == 1) JourneyPanel(api: widget.api, p: p, canEdit: canEdit),
    if (section == 2) EvidencePanel(api: widget.api, p: p, user: widget.user, canEdit: canEdit),
    if (section == 3) AdvisorPanel(api: widget.api, p: p, canEdit: canEdit),
  ]); }));
}

class ResultView extends StatelessWidget {
  const ResultView({super.key, required this.result, this.selectedId, this.onSelect, this.onTrial}); final Map<String, dynamic> result; final String? selectedId; final void Function(String)? onSelect; final void Function(String)? onTrial;
  @override Widget build(BuildContext context) { final candidates = asRows(result['candidates']); final req = asMap(result['requirements']); return Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
    Panel(color: const Color(0xFFEDF4E6), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [const Icon(Icons.info_outline, color: green), const SizedBox(width: 12), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(result['message'] as String, style: const TextStyle(fontWeight: FontWeight.w800)), const SizedBox(height: 5), Text(result['notice'] as String, style: const TextStyle(fontSize: 12, color: muted)), const SizedBox(height: 10), Pill('Model: ${result['model']?['status'] ?? 'not connected'}')]))])), const SizedBox(height: 20),
    Panel(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Your barrier requirements', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w700)), const SizedBox(height: 16), Wrap(spacing: 36, runSpacing: 16, children: [Metric('Max reference OTR', numText(req['max_otr_reference']), req['otr_unit'] as String), Metric('Max reference WVTR', numText(req['max_wvtr_reference']), req['wvtr_unit'] as String), Metric('Storage exposure', '${req['mean_temperature_c']} °C', '${req['mean_rh']}% relative humidity')]), const SizedBox(height: 12), const Text('A dash means this requirement is not calculated for this profile.', style: TextStyle(color: muted, fontSize: 12))])),
    const SizedBox(height: 24), if (candidates.isEmpty) Panel(child: DataView(data: {'Recommended next steps': result['suggested_changes']})),
    ...candidates.asMap().entries.map((e) { final c = e.value, m = asMap(c['material_snapshot']); final tags = asRows(result['choices']).where((x) => x['material_id'] == c['material_id']).map((x) => x['label'] as String).toList(); return Padding(padding: const EdgeInsets.only(bottom: 18), child: Panel(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 44, height: 44, decoration: BoxDecoration(color: e.key == 0 ? lime : paper, borderRadius: BorderRadius.circular(12)), child: Center(child: Text('${e.key + 1}'.padLeft(2, '0'), style: const TextStyle(fontWeight: FontWeight.w800, color: green)))), const SizedBox(width: 14), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('${m['name']}', style: Theme.of(context).textTheme.titleLarge), const SizedBox(height: 4), Text('${m['structure']}', style: const TextStyle(color: muted))])), if (selectedId == c['material_id']) const Pill('Selected')]), const SizedBox(height: 16), Wrap(spacing: 8, runSpacing: 8, children: tags.map((t) => Pill(t)).toList()), const SizedBox(height: 20), Wrap(spacing: 34, runSpacing: 18, children: [Metric('Pack cost', '₹${numText(c['cost_inr'])}', 'Illustrative estimate'), Metric('Quality-life range', '${(c['quality_range_days'] as List).join('–')} d', 'Sensitivity band • not expiry'), Metric('Material use', '${numText(c['material_mass_g'])} g', '${m['thickness_um']} µm thickness'), Metric('Total assumed cost', '₹${numText(c['total_cost_inr'])}', 'Includes your loss assumption')]), const SizedBox(height: 16), ...((c['reasons'] as List).map((r) => Padding(padding: const EdgeInsets.only(bottom: 6), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [const Icon(Icons.check_circle_outline, size: 17, color: green), const SizedBox(width: 8), Expanded(child: Text('$r', style: const TextStyle(fontSize: 13)))])))),
    if (c['model_prediction'] != null) Panel(color: paper, child: DataView(data: c['model_prediction'])),
    ExpansionTile(tilePadding: EdgeInsets.zero, title: const Text('Technical specification & evidence', style: TextStyle(fontSize: 14, fontWeight: FontWeight.w700)), children: [DataView(data: {'Grade': m['grade'], 'OTR': '${m['otr']} ${m['otr_unit']}', 'OTR test': m['otr_test'], 'WVTR': '${m['wvtr']} ${m['wvtr_unit']}', 'WVTR test': m['wvtr_test'], 'Sealant / seal window': '${m['sealant']} · ${m['seal_range_c']}', 'Mechanical requirement': m['mechanical'], 'Recovery route': c['sustainability'], 'Supplier': m['supplier'], 'Required documents': c['documents_needed'], 'Source': m['source'], 'Revision': m['revision']}), if (c['gas'] != null) GasChart(gas: asMap(c['gas']))]),
    if (onSelect != null || onTrial != null) ...[const SizedBox(height: 12), Wrap(spacing: 12, runSpacing: 10, children: [if (onSelect != null) FilledButton.tonal(onPressed: selectedId == c['material_id'] ? null : () => onSelect!(c['material_id'] as String), child: Text(selectedId == c['material_id'] ? 'Selected for trial' : 'Select for trial')), if (onTrial != null) OutlinedButton.icon(onPressed: () => onTrial!(c['material_id'] as String), icon: const Icon(Icons.biotech_outlined, size: 18), label: const Text('Record trial'))])],
    ]))); }),
    if (candidates.length > 1) Panel(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Compare all passing candidates', style: TextStyle(fontWeight: FontWeight.w700, fontSize: 18)), const SizedBox(height: 12), SingleChildScrollView(scrollDirection: Axis.horizontal, child: DataTable(columns: const [DataColumn(label: Text('Material')), DataColumn(label: Text('Cost ₹')), DataColumn(label: Text('Mass g')), DataColumn(label: Text('OTR')), DataColumn(label: Text('WVTR')), DataColumn(label: Text('Recovery'))], rows: candidates.map((c) => DataRow(cells: [DataCell(Text('${c['material_snapshot']['name']}')), DataCell(Text(numText(c['cost_inr']))), DataCell(Text(numText(c['material_mass_g']))), DataCell(Text('${c['material_snapshot']['otr']}')), DataCell(Text('${c['material_snapshot']['wvtr']}')), DataCell(SizedBox(width: 260, child: Text('${c['sustainability']['recovery']}')))])).toList()))])),
    const SizedBox(height: 20), Panel(child: Column(children: [ExpansionTile(tilePadding: EdgeInsets.zero, title: Text('Why alternatives were rejected (${(result['rejected'] as List).length})'), children: asRows(result['rejected']).map((c) => ListTile(contentPadding: EdgeInsets.zero, title: Text('${c['material_snapshot']['name']}'), subtitle: Text((c['failures'] as List).join('\n')))).toList()), ExpansionTile(tilePadding: EdgeInsets.zero, title: const Text('Assumptions & next measurements'), children: [DataView(data: {'Assumptions': result['assumptions'], 'Next measurements': result['next_measurements'], 'Risks': result['risks']})])])),
  ]); }
}
class Metric extends StatelessWidget { const Metric(this.title, this.value, this.note, {super.key}); final String title, value, note; @override Widget build(BuildContext context) => SizedBox(width: 210, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: const TextStyle(color: muted, fontSize: 12)), const SizedBox(height: 5), Text(value, style: const TextStyle(fontSize: 24, fontWeight: FontWeight.w800, color: ink)), const SizedBox(height: 4), Text(note, style: const TextStyle(color: muted, fontSize: 11))])); }
class GasChart extends StatelessWidget { const GasChart({super.key, required this.gas}); final Map<String, dynamic> gas; @override Widget build(BuildContext context) { final rows = asRows(gas['trajectory']); return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const SizedBox(height: 16), const Text('Illustrative atmosphere trajectory', style: TextStyle(fontWeight: FontWeight.w700)), const Text('Green: O₂ · Orange: CO₂ · x: days · y: gas %', style: TextStyle(color: muted, fontSize: 12)), const SizedBox(height: 20), SizedBox(height: 220, child: LineChart(LineChartData(minX: 0, minY: 0, maxY: 25, borderData: FlBorderData(show: false), titlesData: const FlTitlesData(topTitles: AxisTitles(sideTitles: SideTitles(showTitles: false)), rightTitles: AxisTitles(sideTitles: SideTitles(showTitles: false))), lineBarsData: ['o2_pct', 'co2_pct'].asMap().entries.map((e) => LineChartBarData(spots: rows.map((r) => FlSpot((r['day'] as num).toDouble(), (r[e.value] as num).toDouble())).toList(), color: e.key == 0 ? green : Colors.orange, barWidth: 3, dotData: const FlDotData(show: false))).toList()))), const SizedBox(height: 14), DataView(data: {'Initial air': '${gas['initial_o2_pct']}% O₂ / ${gas['initial_co2_pct']}% CO₂', 'Equilibrium': '${gas['equilibrium_o2_pct']}% O₂ / ${gas['equilibrium_co2_pct']}% CO₂', 'Model limits': gas['method'], 'Perforation': gas['microperforation']})]); } }

Future<void> recordTrial(BuildContext context, ApiClient api, String project, String material) async { final saved = await editDialog(context, 'Record a storage trial', const [FormItem('study_id', 'Independent study / batch identifier'), FormItem('observed_days', 'Observed duration (days)', numeric: true), FormItem('failure', 'Observed outcome', value: 'moisture', options: {'moisture': 'Moisture gain', 'oxidation': 'Oxidation', 'wilting': 'Wilting', 'mechanical': 'Mechanical damage', 'microbial': 'Microbial spoilage', 'other': 'Other', 'no_failure_yet': 'No failure yet (censored)'}), FormItem('notes', 'Observation notes', required: false, lines: 3)], (v) async { await api.post('/api/trials', {'project_id': project, 'material_id': material, ...v, 'observed_days': double.parse(v['observed_days']!)}); }); if (saved == true && context.mounted) toast(context, 'Trial saved. Share the project to request independent review.'); }

class JourneyPanel extends StatefulWidget { const JourneyPanel({super.key, required this.api, required this.p, required this.canEdit}); final ApiClient api; final Map<String, dynamic> p; final bool canEdit; @override State<JourneyPanel> createState() => _JourneyPanelState(); }
class _JourneyPanelState extends State<JourneyPanel> {
  late Future<dynamic> logs = widget.canEdit ? widget.api.get('/api/projects/${widget.p['id']}/sensor-logs') : Future.value([]);
  void reload() => setState(() => logs = widget.api.get('/api/projects/${widget.p['id']}/sensor-logs'));
  @override Widget build(BuildContext context) => Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Panel(child: DataView(data: {'Storage journey': widget.p['result']['stages']})), const SizedBox(height: 20), Heading('Sensor observations', subtitle: 'Timestamped temperature and humidity readings.', action: widget.canEdit ? OutlinedButton.icon(onPressed: () => action(context, () async { final file = await pick('csv'); if (file == null) return; await widget.api.upload('/api/projects/${widget.p['id']}/sensor-log', file.bytes!, file.name); reload(); }), icon: const Icon(Icons.upload_file), label: const Text('Import sensor CSV')) : null), const Text('CSV columns: timestamp, temperature_c, relative_humidity. Use timezone-aware timestamps in increasing order.', style: TextStyle(color: muted, fontSize: 12)), const SizedBox(height: 16), LoadView(future: logs, retry: reload, builder: (raw) { final rows = asRows(raw); return rows.isEmpty ? const Empty('No sensor logs', 'Import actual conditions to reassess this packaging scenario.') : Column(children: rows.map((r) => Padding(padding: const EdgeInsets.only(bottom: 14), child: Panel(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('${r['readings']} readings · ${r['duration_days']} days', style: const TextStyle(fontWeight: FontWeight.w700)), const SizedBox(height: 10), Text('${r['mean_temperature_c']} °C time-weighted average · ${r['mean_rh']}% RH'), Text('${r['excursion_readings']} temperature excursion readings', style: const TextStyle(color: muted)), const SizedBox(height: 12), OutlinedButton(onPressed: () => action(context, () async { final result = asMap(await widget.api.post('/api/projects/${widget.p['id']}/sensor-logs/${r['id']}/simulate')); if (context.mounted) await Navigator.push(context, MaterialPageRoute<void>(builder: (_) => Scaffold(appBar: AppBar(title: const Text('Measured-condition scenario')), body: PageBody(children: [Panel(child: Text(result['note'] as String)), const SizedBox(height: 16), ResultView(result: asMap(result['scenario']))])))); }), child: const Text('Reassess measured conditions'))])))).toList()); })]);
}

class EvidencePanel extends StatefulWidget { const EvidencePanel({super.key, required this.api, required this.p, required this.user, required this.canEdit}); final ApiClient api; final Map<String, dynamic> p, user; final bool canEdit; @override State<EvidencePanel> createState() => _EvidencePanelState(); }
class _EvidencePanelState extends State<EvidencePanel> {
  late Future<dynamic> data = load(); Future<dynamic> load() => Future.wait([widget.api.get('/api/projects/${widget.p['id']}/documents'), widget.api.get('/api/projects/${widget.p['id']}/history')]); void reload() => setState(() => data = load());
  Future<void> upload() async { final file = await pick('pdf'); if (file == null || !mounted) return; await editDialog(context, 'Attach evidence PDF', const [FormItem('title', 'Document title'), FormItem('scope', 'Food, material and intended-use scope', lines: 3), FormItem('expiry_date', 'Expiry date (YYYY-MM-DD)', required: false)], (v) async { await widget.api.upload('/api/documents', file.bytes!, file.name, fields: {...v, 'project_id': widget.p['id'] as String}); }); reload(); }
  @override Widget build(BuildContext context) => Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Heading('Evidence & review history', subtitle: 'Keep your documents and decisions together.', action: widget.canEdit ? OutlinedButton.icon(onPressed: () => action(context, upload), icon: const Icon(Icons.attach_file), label: const Text('Attach PDF')) : null), LoadView(future: data, retry: reload, builder: (raw) { final docs = asRows(raw[0]), events = asRows(raw[1]); return Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [if (docs.isEmpty) const Empty('No evidence attached', 'Add food-contact declarations, supplier reports or storage test results.'), ...docs.map((d) => Padding(padding: const EdgeInsets.only(bottom: 12), child: Panel(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(d['title'] as String, style: const TextStyle(fontWeight: FontWeight.w700)), const SizedBox(height: 8), Text(d['scope'] as String), const SizedBox(height: 8), Pill(d['expired'] == true ? 'Expired' : human(d['status']), warning: d['status'] != 'accepted_for_scope' || d['expired'] == true), Wrap(spacing: 10, children: [TextButton(onPressed: () => action(context, () async { await widget.api.download('/api/documents/${d['id']}/download', 'evidence', 'pdf'); }), child: const Text('Download')), if (!widget.canEdit && widget.user['is_reviewer'] == true) TextButton(onPressed: () async { await editDialog(context, 'Review document scope', const [FormItem('status', 'Decision', value: 'accepted_for_scope', options: {'accepted_for_scope': 'Accepted for stated scope', 'changes_requested': 'Changes requested'}), FormItem('notes', 'Review notes', lines: 3)], (v) async { await widget.api.post('/api/documents/${d['id']}/review', v); }); reload(); }, child: const Text('Review evidence'))]), if (d['notes'] != null) Text('Review: ${d['notes']}')])))), const SizedBox(height: 18), Panel(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Expert decisions', style: TextStyle(fontWeight: FontWeight.w700)), const SizedBox(height: 12), DataView(data: (widget.p['reviews'] as List).isEmpty ? 'No expert review yet.' : widget.p['reviews'])])), const SizedBox(height: 18), Panel(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Project timeline', style: TextStyle(fontWeight: FontWeight.w700)), ...events.map((e) => ListTile(contentPadding: EdgeInsets.zero, leading: const Icon(Icons.history, color: green), title: Text(titleCase(e['action'])), subtitle: Text(dateText(e['created_at'])), onTap: () => showData(context, titleCase(e['action']), e['data'])))]))]); })]);
}

class AdvisorPanel extends StatefulWidget { const AdvisorPanel({super.key, required this.api, required this.p, required this.canEdit}); final ApiClient api; final Map<String, dynamic> p; final bool canEdit; @override State<AdvisorPanel> createState() => _AdvisorPanelState(); }
class _AdvisorPanelState extends State<AdvisorPanel> {
  final question = TextEditingController(); final tts = FlutterTts(); Map<String, dynamic>? answer; bool asking = false;
  @override void dispose() { question.dispose(); tts.stop(); super.dispose(); }
  Future<void> ask() async { if (question.text.trim().length < 3) return; setState(() => asking = true); await action(context, () async { final result = asMap(await widget.api.post('/api/projects/${widget.p['id']}/assistant', {'question': question.text.trim()})); if (mounted) setState(() => answer = result); }); if (mounted) setState(() => asking = false); }
  @override Widget build(BuildContext context) => Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Panel(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Ask about this recommendation', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w700)), const SizedBox(height: 8), const Text('Answers refer to this saved record. The guide covers cost, barriers, shelf life and sustainability.', style: TextStyle(color: muted)), const SizedBox(height: 18), TextField(controller: question, decoration: const InputDecoration(hintText: 'Why does this material cost more?', prefixIcon: Icon(Icons.chat_bubble_outline)), onSubmitted: (_) => ask()), const SizedBox(height: 12), FilledButton(onPressed: asking ? null : ask, child: Text(asking ? 'Reading the record…' : 'Ask the packaging guide')), if (answer != null) ...[const SizedBox(height: 16), Text(answer!['answer'] as String), const SizedBox(height: 8), Text('Source: ${answer!['source']}', style: const TextStyle(fontSize: 12, color: muted)), TextButton.icon(onPressed: () => action(context, () async { await tts.setLanguage('en-IN'); await tts.speak(answer!['answer'] as String); }), icon: const Icon(Icons.volume_up_outlined), label: const Text('Read answer aloud'))]])), const SizedBox(height: 18), Wrap(spacing: 12, runSpacing: 12, children: [if (widget.canEdit) OutlinedButton.icon(onPressed: () => action(context, () async { final d = await widget.api.get('/api/projects/${widget.p['id']}/audit'); if (context.mounted) await showData(context, 'Existing-pack audit', d); }), icon: const Icon(Icons.find_in_page_outlined), label: const Text('Audit current packaging')), if (widget.canEdit) OutlinedButton.icon(onPressed: () => action(context, () async { await editDialog(context, 'Match saved supplier quotations', const [FormItem('moq', 'Maximum minimum-order quantity (kg)', value: '1000', numeric: true), FormItem('lead', 'Maximum lead time (days)', value: '30', numeric: true)], (v) async { final d = await widget.api.get('/api/projects/${widget.p['id']}/supplier-matches?max_moq_kg=${v['moq']}&max_lead_days=${v['lead']}'); if (context.mounted) await showData(context, 'Supplier matches', d); }); }), icon: const Icon(Icons.storefront_outlined), label: const Text('Find matching suppliers')), OutlinedButton.icon(onPressed: () => action(context, () async { final d = await widget.api.get('/api/projects/${widget.p['id']}/handling-advice'); if (context.mounted) await showData(context, 'Secondary & active packaging review', d); }), icon: const Icon(Icons.local_shipping_outlined), label: const Text('Handling & active options'))])]);
}
