part of '../main.dart';

const translations = {
  'en': ['Overview', 'New recommendation', 'Projects', 'Materials & foods', 'Trials', 'Batches & QR', 'Imports & evidence', 'Suppliers', 'Expert reviews', 'Research', 'Feedback', 'Offline library', 'Settings'],
  'hi': ['अवलोकन', 'नई सिफारिश', 'परियोजनाएँ', 'सामग्री और खाद्य', 'परीक्षण', 'बैच और QR', 'आयात और दस्तावेज़', 'आपूर्तिकर्ता', 'विशेषज्ञ समीक्षा', 'अनुसंधान', 'प्रतिक्रिया', 'ऑफलाइन संग्रह', 'सेटिंग्स'],
  'gu': ['ઝાંખી', 'નવી ભલામણ', 'પ્રોજેક્ટ્સ', 'સામગ્રી અને ખોરાક', 'પરીક્ષણો', 'બેચ અને QR', 'આયાત અને પુરાવા', 'સપ્લાયર્સ', 'નિષ્ણાત સમીક્ષા', 'સંશોધન', 'પ્રતિસાદ', 'ઓફલાઇન સંગ્રહ', 'સેટિંગ્સ'],
  'mr': ['आढावा', 'नवीन शिफारस', 'प्रकल्प', 'साहित्य आणि अन्न', 'चाचण्या', 'बॅच आणि QR', 'आयात आणि पुरावे', 'पुरवठादार', 'तज्ज्ञ पुनरावलोकन', 'संशोधन', 'अभिप्राय', 'ऑफलाइन संग्रह', 'सेटिंग्ज'],
};
const navIcons = [Icons.grid_view_rounded, Icons.add_box_outlined, Icons.folder_open_rounded, Icons.layers_outlined, Icons.biotech_outlined, Icons.qr_code_2_rounded, Icons.cloud_upload_outlined, Icons.storefront_outlined, Icons.fact_check_outlined, Icons.science_outlined, Icons.chat_bubble_outline_rounded, Icons.offline_pin_outlined, Icons.settings_outlined];
class Shell extends StatefulWidget { const Shell({super.key, required this.api, required this.user, required this.onLogout, required this.onProfile}); final ApiClient api; final Map<String, dynamic> user; final Future<void> Function() onLogout; final Future<void> Function(Map<String, dynamic>) onProfile; @override State<Shell> createState() => _ShellState(); }
class _ShellState extends State<Shell> {
  int selected = 0, refresh = 0; late String language = widget.api.prefs?.getString('language') ?? 'en';
  List<int> get visible => widget.api.offline ? [11, 12] : [0, 1, 2, 3, 4, 5, if (widget.user['role'] != 'farmer') 6, if (widget.user['role'] != 'farmer') 7, if (widget.user['is_reviewer'] == true) 8, if (widget.user['role'] == 'researcher') 9, 10, 11, 12];
  void go(int index) => setState(() { selected = index; refresh++; });
  Widget page() {
    final api = widget.api, user = widget.user;
    switch (selected) {
      case 0: return Dashboard(api: api, user: user, go: go);
      case 1: return BriefPage(api: api, user: user, language: language, onSaved: () => go(2));
      case 2: return ProjectsPage(api: api, user: user, newBrief: () => go(1));
      case 3: return CatalogPage(api: api, user: user);
      case 4: return TrialsPage(api: api, user: user);
      case 5: return BatchesPage(api: api, user: user);
      case 6: return ImportsPage(api: api, user: user);
      case 7: return SuppliersPage(api: api);
      case 8: return ReviewPage(api: api, user: user);
      case 9: return ResearchPage(api: api, user: user);
      case 10: return FeedbackPage(api: api);
      case 11: return OfflinePage(api: api, user: user);
      default: return SettingsPage(api: api, user: user, onProfile: widget.onProfile, onReconnect: () async { widget.api.offline = false; try { await api.get('/api/auth/me'); go(0); } catch (_) { widget.api.offline = true; rethrow; } });
    }
  }
  Widget navigation(bool wide) => Container(width: 250, color: Colors.white, child: SafeArea(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Padding(padding: EdgeInsets.all(25), child: Brand()), Padding(padding: const EdgeInsets.symmetric(horizontal: 26, vertical: 5), child: Text('${titleCase(widget.user['role'])} workspace', style: const TextStyle(fontSize: 12, color: muted))), const SizedBox(height: 18), Expanded(child: ListView(padding: const EdgeInsets.symmetric(horizontal: 14), children: visible.map((i) => Padding(padding: const EdgeInsets.only(bottom: 5), child: ListTile(dense: true, selected: i == selected, selectedColor: green, selectedTileColor: const Color(0xFFEDF4E6), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)), leading: Icon(navIcons[i], size: 21), title: Text(translations[language]![i], style: TextStyle(fontSize: 13, fontWeight: i == selected ? FontWeight.w800 : FontWeight.w500)), onTap: () { go(i); if (!wide) Navigator.pop(context); }))).toList())), Padding(padding: const EdgeInsets.all(20), child: Panel(padding: 14, color: paper, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Row(children: [Icon(Icons.verified_outlined, color: green, size: 18), SizedBox(width: 8), Text('Know your evidence', style: TextStyle(fontSize: 12, fontWeight: FontWeight.w700))]), const SizedBox(height: 8), const Text('Catalog data is illustrative. Validate your pack with real trials.', style: TextStyle(fontSize: 11, color: muted, height: 1.5)), const SizedBox(height: 8), TextButton(onPressed: () => go(4), child: const Text('Open trial workspace →', style: TextStyle(fontSize: 11)))]))), ])));
  @override Widget build(BuildContext context) {
    if (!visible.contains(selected)) selected = visible.first;
    final wide = MediaQuery.sizeOf(context).width >= 1080;
    return Scaffold(drawer: wide ? null : Drawer(child: navigation(false)), body: Row(children: [if (wide) navigation(true), Expanded(child: Column(children: [Container(height: 80, decoration: const BoxDecoration(color: Colors.white, border: Border(bottom: BorderSide(color: line))), padding: const EdgeInsets.symmetric(horizontal: 20), child: Row(children: [if (!wide) Builder(builder: (context) => IconButton(onPressed: () => Scaffold.of(context).openDrawer(), icon: const Icon(Icons.menu))), Expanded(child: Text(translations[language]![selected], style: const TextStyle(fontWeight: FontWeight.w700))), if (MediaQuery.sizeOf(context).width > 620) Pill(widget.api.offline ? 'Offline • read only' : 'Workspace connected'), const SizedBox(width: 12), DropdownButtonHideUnderline(child: DropdownButton<String>(value: language, items: const [DropdownMenuItem(value: 'en', child: Text('EN')), DropdownMenuItem(value: 'hi', child: Text('हिंदी')), DropdownMenuItem(value: 'gu', child: Text('ગુજ')), DropdownMenuItem(value: 'mr', child: Text('मर'))], onChanged: (v) async { if (v == null) return; await widget.api.prefs?.setString('language', v); if (mounted) setState(() => language = v); })), IconButton(tooltip: 'Notifications', onPressed: widget.api.offline ? null : () => action(context, () async { final data = await widget.api.get('/api/notifications'); if (context.mounted) await showData(context, 'Workspace updates', (data as List).isEmpty ? 'You are up to date.' : data); }), icon: const Icon(Icons.notifications_none_rounded)), const SizedBox(width: 6), PopupMenuButton<String>(onSelected: (v) => v == 'logout' ? widget.onLogout() : go(12), itemBuilder: (_) => [PopupMenuItem(enabled: false, child: Text(widget.user['email'] as String)), const PopupMenuItem(value: 'settings', child: Text('Account settings')), const PopupMenuItem(value: 'logout', child: Text('Sign out'))], child: CircleAvatar(backgroundColor: lime, foregroundColor: ink, child: Text((widget.user['name'] as String).substring(0, 1).toUpperCase())))])), Expanded(child: KeyedSubtree(key: ValueKey('$selected-$refresh'), child: page()))]))]));
  }
}

class Dashboard extends StatefulWidget { const Dashboard({super.key, required this.api, required this.user, required this.go}); final ApiClient api; final Map<String, dynamic> user; final void Function(int) go; @override State<Dashboard> createState() => _DashboardState(); }
class _DashboardState extends State<Dashboard> {
  late Future<dynamic> data = widget.api.get('/api/dashboard'); void reload() => setState(() => data = widget.api.get('/api/dashboard'));
  @override Widget build(BuildContext context) => LoadView(future: data, retry: reload, builder: (raw) { final d = asMap(raw), role = widget.user['role']; return PageBody(children: [
    Heading('Good to see you, ${widget.user['name'].toString().split(' ').first}.', subtitle: 'Your packaging decisions, all in one place.', action: FilledButton.icon(onPressed: () => widget.go(1), icon: const Icon(Icons.add, size: 18), label: const Text('New recommendation'))),
    Container(padding: const EdgeInsets.all(28), decoration: BoxDecoration(color: ink, borderRadius: BorderRadius.circular(24)), child: LayoutBuilder(builder: (context, box) => Row(children: [Expanded(flex: 3, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Pill('${titleCase(role)} workspace'), const SizedBox(height: 16), Text(role == 'farmer' ? 'Give your harvest\na better journey.' : role == 'researcher' ? 'Turn packaging trials\ninto trusted evidence.' : 'The right pack.\nFor every product.', style: const TextStyle(fontSize: 31, height: 1.15, fontWeight: FontWeight.w800, color: Colors.white, letterSpacing: -.8)), const SizedBox(height: 14), Text(role == 'farmer' ? 'Explore breathable films, storage conditions and crop protection.' : role == 'researcher' ? 'Review shared studies, check material evidence and export validated outcomes.' : 'Compare material performance, cost and sourcing in a single workflow.', style: const TextStyle(color: Color(0xFFBCD0C4), height: 1.5)), const SizedBox(height: 20), FilledButton.icon(style: FilledButton.styleFrom(backgroundColor: lime, foregroundColor: ink), onPressed: () => widget.go(role == 'researcher' ? 9 : 1), icon: const Icon(Icons.arrow_forward_rounded, size: 18), label: Text(role == 'researcher' ? 'Open research workspace' : 'Find a packaging match'))])), if (box.maxWidth > 700) const Expanded(flex: 2, child: SizedBox(height: 210, child: PackagingArt()))]))),
    const SizedBox(height: 24), Wrap(spacing: 16, runSpacing: 16, children: [Stat('Saved projects', '${d['projects']}', Icons.folder_outlined), Stat('Recorded trials', '${d['trials']}', Icons.biotech_outlined), Stat('Tracked batches', '${d['batches']}', Icons.qr_code_2), Stat('Needs attention', '${d['needs_attention']}', Icons.flag_outlined)]),
    const SizedBox(height: 30), Heading('Recent projects', subtitle: 'Pick up where you left off.', action: TextButton(onPressed: () => widget.go(2), child: const Text('View all projects →'))),
    if ((d['recent_projects'] as List).isEmpty) Empty('Your first better pack starts here', 'Create a product brief to compare suitable materials.', icon: Icons.inventory_2_outlined, action: OutlinedButton(onPressed: () => widget.go(1), child: const Text('Create a product brief'))) else Panel(padding: 8, child: Column(children: asRows(d['recent_projects']).map((p) => ProjectTile(p: p, onTap: () => openProject(context, widget.api, widget.user, p['id'] as String))).toList())),
    const SizedBox(height: 24), Wrap(spacing: 16, runSpacing: 16, children: [SizedBox(width: 340, child: Panel(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Icon(Icons.layers_outlined, color: green), const SizedBox(height: 14), const Text('Explore the material library', style: TextStyle(fontWeight: FontWeight.w700)), const SizedBox(height: 8), Text('${d['materials']} material variants · ${d['foods']} food profiles', style: const TextStyle(color: muted)), TextButton(onPressed: () => widget.go(3), child: const Text('Browse catalog →'))]))), SizedBox(width: 340, child: Panel(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Icon(Icons.insights_outlined, color: green), const SizedBox(height: 14), const Text('Learn from your trials', style: TextStyle(fontWeight: FontWeight.w700)), const SizedBox(height: 8), Text((d['failure_counts'] as Map).isEmpty ? 'Your observed outcomes will appear here.' : (d['failure_counts'] as Map).entries.map((e) => '${human(e.key)}: ${e.value}').join(' · '), style: const TextStyle(color: muted)), TextButton(onPressed: () => widget.go(4), child: const Text('Open trials →'))])))]),
  ]); });
}
class ProjectTile extends StatelessWidget { const ProjectTile({super.key, required this.p, required this.onTap}); final Map<String, dynamic> p; final VoidCallback onTap; @override Widget build(BuildContext context) => ListTile(contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8), leading: Container(padding: const EdgeInsets.all(12), decoration: BoxDecoration(color: paper, borderRadius: BorderRadius.circular(12)), child: const Icon(Icons.inventory_2_outlined, color: green)), title: Text('${p['name']}', style: const TextStyle(fontWeight: FontWeight.w700)), subtitle: Text('${p['food_name']} · ${p['target_days']} days · ${dateText(p['created_at'])}'), trailing: MediaQuery.sizeOf(context).width < 500 ? const Icon(Icons.chevron_right) : Pill('${p['candidate_count']} candidates', warning: p['candidate_count'] == 0), onTap: onTap); }
Future<void> openProject(BuildContext context, ApiClient api, Map<String, dynamic> user, String id) async { await Navigator.push(context, MaterialPageRoute<void>(builder: (_) => ProjectPage(api: api, user: user, id: id))); }
class ProjectsPage extends StatefulWidget { const ProjectsPage({super.key, required this.api, required this.user, required this.newBrief}); final ApiClient api; final Map<String, dynamic> user; final VoidCallback newBrief; @override State<ProjectsPage> createState() => _ProjectsPageState(); }
class _ProjectsPageState extends State<ProjectsPage> { late Future<dynamic> data = widget.api.get('/api/projects'); String query = ''; void reload() => setState(() => data = widget.api.get('/api/projects'));
  @override Widget build(BuildContext context) => PageBody(children: [Heading('Your packaging projects', subtitle: 'Compare, test and refine your packaging choices.', action: FilledButton.icon(onPressed: widget.newBrief, icon: const Icon(Icons.add), label: const Text('New brief'))), TextField(decoration: const InputDecoration(hintText: 'Search by project or food name', prefixIcon: Icon(Icons.search)), onChanged: (v) => setState(() => query = v.toLowerCase())), const SizedBox(height: 20), LoadView(future: data, retry: reload, builder: (raw) { final rows = asRows(raw).where((p) => '${p['name']} ${p['food_name']}'.toLowerCase().contains(query)).toList(); return rows.isEmpty ? const Empty('No projects found', 'Create a brief or try another search.') : Panel(padding: 8, child: Column(children: rows.map((p) => ProjectTile(p: p, onTap: () async { await openProject(context, widget.api, widget.user, p['id'] as String); reload(); })).toList())); })]);
}
